version: "3.2"
services:
  main:
    image: jenkins/jenkins:2.164-alpine
    deploy:
      resources:
        limits:
          memory: 400m
        reservations:
          memory: 50m
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/jenkins
        - com.df.port=8080
      placement:
        constraints:
          - node.labels.env == jenkins-master
    ports:
      - 50000:50000
    environment:
      - JENKINS_OPTS=--prefix=/jenkins
      - USER=admin
      - PASSWORD=123456
    networks:
      - network1


    volumes:
      - type: bind
        source: /var/jenkins_home
        target: /var/jenkins_home

  agent:
    image: vfarcic/jenkins-swarm-agent
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: /workspace
        target: /workspace
    environment:
      - COMMAND_OPTIONS=-master http://10.130.129.237/jenkins -username $USER -password $PASS -labels 'docker' -executors 5
      - USER=admin
      - PASS=123456
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.env1 == jenkins-agent
networks:
  network1:
    external: true
