version: "3.4"
services:
  main:
    image: registry:2.5.0
    ports:
      - 5000:5000
    volumes:
      - type: bind
        source: $PWD
        target: /var/lib/registry
    deploy:
      resources:
        reservations:
          memory: 100m
